language: shell

os: "windows"

branches:
  except:
    - master
    - /^untagged/
    - /^TRAVIS/
  only:
    - dev
    - travis-windows
    - range_card_parser

cache:
  directories:
    - /c/Strawberry



install:
  - ls /c/Strawberry 2>/dev/null
  - if [[ -d /c/Strawberry ]]; then echo "Strawberry from cache."; else echo "Strawberry missing";chocolatey.exe install StrawberryPerl;fi
  - export PATH="/c/Strawberry/perl/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/c/bin:$PATH"
  - export PERL5LIB="/c/Strawberry/perl/lib:/c/Strawberry/perl/site/lib:/c/Strawberry/perl/vendor/lib"
  - LASTPATH=$(pwd)
  - cd /c/Strawberry/perl/bin
  - if [[ -f /c/Strawberry/perl/site/bin/pp.bat ]]; then echo "PP from cache."; else cpanm.bat -f -n pp || cat /c/Users/travis/.cpanm/work/*/build.log;fi
  - ls /c/Strawberry/perl/site/bin
  - cd $LASTPATH

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
# Help test
  - /c/Strawberry/perl/bin/perl ./Range\ Cards/src/range_card_parser/range_card_parser.pl -h
# Library reading
  - /c/Strawberry/perl/bin/perl ./Range\ Cards/src/range_card_parser/range_card_parser.pl -l -i ./Range\ Cards/data/Universal\ Reticle\ MRAD.txt -ii ./Range\ Cards/data/Universal\ Reticle\ MRAD\ legend.txt
# Range Card Generation Simulation and comparison with test file (1st line not included)
  - /c/Strawberry/perl/bin/perl ./Range\ Cards/src/range_card_parser/range_card_parser.pl -rl 150,200,250 -rs 10,20 -c "B1/SNAKEBITE" "L1/45-70" "M1/.243" -i ./Range\ Cards/data/Universal\ Reticle\ MRAD.txt -ii ./Range\ Cards/data/Universal\ Reticle\ MRAD\ legend.txt -s|tail -n 8| diff - ./Range\ Cards/src/test/range_card_test.txt
# Make a link for perl script is right place (no symbolic is available here)
  - rm -f ./Range\ Cards/range_card_parser.pl
  - ln -f ./Range\ Cards/src/range_card_parser/range_card_parser.pl ./Range\ Cards/range_card_parser.pl
# Pack into new exe
  - rm -f ./Range\ Cards/range_card_parser.exe
  - cd /c/Strawberry/perl/site/bin
  - pp.bat -o ${LASTPATH}/Range\ Cards/range_card_parser.exe ${LASTPATH}/Range\ Cards/src/range_card_parser/range_card_parser.pl
  - cd ${LASTPATH}
  - ls -la ./Range\ Cards/

after_success:
  #Set up git user name and tag this commit
  - git config --local user.name "silvan78"
  - git config --local user.email "lukasz.knizewski+github@gmail.com"
  - export TRAVIS_TAG="TRAVIS-"$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)
#  - git tag $TRAVIS_TAG
  #Setup credentials
#  - git config credential.helper "store --file=../.git/credentials"
#  - echo "https://${GITHUB_TOKEN}:@github.com" > ../.git/credentials
  - git remote set-url origin https://$GITHUB_TOKEN@github.com/silvan78/theHunterClassic_Better_Reticles.git
  #Deploy to current branch
  - git add .
  - git commit -m "$TRAVIS_TAG deploy"
  - git tag $TRAVIS_TAG
  - git push origin $BRANCH --tags $TRAVIS_TAG
#  - git push -f -q https://$GITHUB_TOKEN@github.com/silvan78/theHunterClassic_Better_Reticles.git $TRAVIS_TAG

#before_deploy:
#  # Set up git user name and tag this commit
#  - git config --local user.name "silvan78"
#  - git config --local user.email "lukasz.knizewski+github@gmail.com"
#  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
#  - git tag $TRAVIS_TAG

#deploy:
#  provider: releases
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
#  keep_history: true
#  file:
#    - ./Range\ Cards/range_card_parser.exe
#    - ./Range\ Cards/range_card_parser.pl
#  overwrite: true
#  draft: true
#  on:
#    tags: true
#    branch:
#      master
