language: shell
os: "windows"
install:
  - chocolatey.exe install StrawberryPerl -y
  - export PATH=/c/Strawberry/perl/bin:/c/Strawberry/perl/site/bin:$PATH
  - export PERL5LIB="/c/Strawberry/perl/lib:/c/Strawberry/perl/site/lib:/c/Strawberry/perl/vendor/lib"
  - LASTPATH=$(pwd)
  - cd /c/Strawberry/perl/bin
  - cpan.bat -Ti pp || ls /c/Strawberry/perl/site/bin
  - cd $LASTPATH
script:
# Help test
  - /c/Strawberry/perl/bin/perl ./Range\ Cards/range_card_parser/src/range_card_parser.pl -h
# Library reading
  - /c/Strawberry/perl/bin/perl ./Range\ Cards/range_card_parser/src/range_card_parser.pl -l -i ./Range\ Cards/data/Universal\ Reticle\ MRAD.txt -ii ./Range\ Cards/data/Universal\ Reticle\ MRAD\ legend.txt
# Range Card Generation Simulation and comparison with test file (1st line not included)
  - /c/Strawberry/perl/bin/perl ./Range\ Cards/range_card_parser/src/range_card_parser.pl -rl 150,200,250 -rs 10,20 -c "B1/SNAKEBITE" "L1/45-70" "M1/.243" -i ./Range\ Cards/data/Universal\ Reticle\ MRAD.txt -ii ./Range\ Cards/data/Universal\ Reticle\ MRAD\ legend.txt -s|tail -n 8| diff - ./Range\ Cards/range_card_parser/test/range_card_test.txt
# Make a link in Range Cards
  - ln -sf ./Range\ Cards/range_card_parser/src/range_card_parser.pl ./Range\ Cards/range_card_parser.pl
# Build new exe
  - cd /c/Strawberry/perl/site/bin
  - pp.bat -o ${LASTPATH}/Range\ Cards/range_card_parser.exe ${LASTPATH}/Range\ Cards/range_card_parser/src/range_card_parser.pl
  - cd ${LASTPATH}
  - ls -l ./Range\ Cards/
# TODO: deploy succesful packing
# TODO: cache build env (/c/Strawberry)



